import type { Metadata } from "next"
import "./globals.css"
import { ColorProvider } from '@/components/color-provider'
import Layout from '@/components/layout'
import { ThemeProvider } from '@/components/theme-provider'
import { geistMono, geistSans } from '@/fonts'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <ColorProvider>
            <Layout>
              {children}
            </Layout>
          </ColorProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
